### ISSUE TITLE
无限重启

### ISSUE THREAD

**Issue by wang-xianke** [huzhimaye/Hackintosh-H610ITX-12400F-6750GRE#1]
我的是12400f MS-H910i 6600xt，用这个无限重启是咋回事啊，能不能答复我一下

**Comment by wang-xianke** [comment]
Mine is 12400f MS-H910i 6600xt, with this unlimited restart is what is going on, can you reply to me

**Comment by huzhimaye** [comment]
6600xt is not supported. Please try WhateverGreen.kext.

**Comment by wang-xianke** [comment]
OK，Do I find this driver again to replace it?
