### ISSUE TITLE
hackintosh failed

### ISSUE THREAD

**Issue by 12711** [huzhimaye/Hackintosh-H610ITX-12400F-6750GRE#2]
Hello, I purchased it according to your hardware configuration and installed it according to your efi, but the following error occurred. Could you please help me check it out?

my hardware is :
主板： 铭瑄挑战者H610itx 2.5G    
CPU：intel i5 12400F
CPU散热：利民 XP90-X53
显卡: powercolor RX 6750 gre 10g
硬盘: 固态 1T
内存： 32G-64G
WiFi & 蓝牙: BCM943602CS & NGFF Adapter 
电源：Almordor SFX650
机箱： SHINY SNAKE S300 8.1L 
散热风扇：Thermalright 8015*2 &12025

[opencore-2024-10-06-195612.txt](https://github.com/user-attachments/files/17273043/opencore-2024-10-06-195612.txt)

**Comment by huzhimaye** [comment]
looks like some quirk don't match to firmware specs, please check: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start
